# ROOTS SECTION
mp_glob_sub_win_drive: 'C:/'
mp_glob_sub_wsl_drive: '/mnt/c/'
mp_glob_sub_lin_drive: '/'
mp_glob_mac_drive: '/'

#Use Mounted WSL drive for Linux and Mac
mp_glob_sub_win_user_mnt: 'Users'
mp_glob_sub_wsl_user_mnt: 'home'
mp_glob_sub_lin_user_mnt: 'home'
mp_glob_mac_user_mnt: 'Users'

# Hard Coded Username override with get username
mp_glob_sub_win_user: 'shepa'
mp_glob_sub_wsl_user: 'shepa'
mp_glob_sub_lin_user: 'shepa'
mp_glob_sub_mac_user: 'shepa'
mp_glob_sub_user: 'shepa'


#Mount Point 
mp_glob_runtype: 'onedrive' # localdrive, onedrive, or wsl
mp_glob_sub_netdrive: 'OneDrive' # WinRunmnt1, OneDrive, or WinRunmnt2

#Common SECTION onedrive and localdrive
mp_glob_sub_dir1: '8.0 Projects'
mp_glob_sub_dir2: '8.3 ProjectModelsEquinox'

#Platform Mount Points
mp_glob_sub_platform_win: 'EQUINRUN'
mp_glob_sub_platform_lin: 'EQUINRUNLIN'
mp_glob_sub_platform_mac: 'EQUINRUNLMAC'
mp_glob_sub_platform: 'EQUINRUN'

# Run libraries
mp_glob_sub_ml_src_lib: 'PythonLib'
mp_glob_sub_ml_src_modeldata: 'tsModelData'
mp_glob_sub_ml_src_configdata: 'tsConfigData'
mp_glob_sub_ml_directory: 'tshybrid_ensemble_tuning_dir'
mp_glob_sub_ml_model_name: 'prjEquinox1_prod'
mp_glob_sub_ml_baseuniq: '1'

#Logs
mp_glob_sub_ml_logs: 'Logdir'
mp_glob_sub_ml_logs_file: 'prjEquinox1.txt'

#MQL SECTION
mp_glob_sub_data: 'Mql5Data'
mp_glob_mql5_base_ver: 'MQL5'
mp_glob_mql5_base_broker: 'Brokers'
mp_glob_mql5_base_broker_name: 'Metaquotes'
mp_glob_sub_mql_dir1: 'MQL5'
mp_glob_sub_mql_dir2: 'Files'
mp_glob_sub_mql_dir3: 'Include'
mp_glob_sub_mql_dir4: 'Libraries'
mp_glob_sub_mql_dir5: 'Scripts'
mp_glob_sub_mql_dir6: 'Experts'
mp_glob_sub_mql_dir7: 'Indicators'
