py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlappparams
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlbaseparams==2.6.14
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlconnect==2.5.37
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqldataLoader==2.6.24
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqldataparams==2.5.28
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqldataprocess==2.7.59
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlenvcore==2.5.14
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlenvmgr==2.7.16
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlmlparams==2.5.8
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlmlprocess==2.7.55
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlmltuner==2.4.73
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlmltunerparams==2.5.25
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqloverrides==2.7.32
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlplatform==2.3.29
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlreference==2.3.26
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlsetup==2.4.1
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps --upgrade tsmqlutilities==2.8.29