# config.yaml


# General Settings
#mv_data_dfname1: 'df_rates1'
#mv_data_dfname2: 'df_rates2'
#mp_data_filename1: 'tickdata1.csv'
#mp_data_filename2: 'ratesdata1.csv'

# User and Project Information
drive: 'C:\\'
user: 'shepa'
project: '8.0 Projects'
projectmodel: '8.3 ProjectModelsEquinox'
projectmodelname: 'custom_project_model'  # Override if needed
platformdir: 'Mql5Data'

# Machine Learning Paths
mp_ml_src_lib: 'PythonLib'
mp_ml_src_data: 'tsModelData'
mp_ml_directory: 'tshybrid_ensemble_tuning_prod'
mp_ml_project_name: 'prjEquinox1_prod.keras'
mp_ml_baseuniq: '1'